"""60-day project registry. Used by all automation scripts."""

PROJECTS = [
    # BEGINNER — Days 1-14
    {"day":1,  "title":"AI Chatbot with GitHub Models",         "phase":"beginner",     "tags":["Python","LLM","CLI"],
     "desc":"Build a CLI chatbot with multi-turn memory using GitHub Models. Learn API calls, message arrays, streaming."},
    {"day":2,  "title":"Prompt Engineering Playground",         "phase":"beginner",     "tags":["Prompting","Python","Logging"],
     "desc":"Test zero-shot, few-shot, and chain-of-thought prompts side by side and log outputs for comparison."},
    {"day":3,  "title":"AI Text Summarizer Web App",            "phase":"beginner",     "tags":["Flask","NLP","Chunking"],
     "desc":"Flask app that accepts long text, chunks it, and returns a structured bullet-point summary."},
    {"day":4,  "title":"Sentiment Analysis Tool",               "phase":"beginner",     "tags":["NLP","Classification","Python"],
     "desc":"Classify product reviews as positive/neutral/negative. Compare LLM vs rule-based approach."},
    {"day":5,  "title":"AI Code Explainer",                     "phase":"beginner",     "tags":["DevTools","Python","Multi-lang"],
     "desc":"Paste any code, receive a plain-English explanation with complexity analysis and potential bugs flagged."},
    {"day":6,  "title":"Resume Parser with AI",                 "phase":"beginner",     "tags":["PDF","JSON","Extraction"],
     "desc":"Upload a PDF resume, extract structured JSON (name, skills, experience) using an LLM with output schema."},
    {"day":7,  "title":"Daily News Digest Bot",                 "phase":"beginner",     "tags":["RSS","Email","Automation"],
     "desc":"Fetch RSS feeds, summarize top 5 stories, email yourself the digest. Intro to multi-source aggregation."},
    {"day":8,  "title":"AI-Powered README Generator",           "phase":"beginner",     "tags":["GitHub API","DevTools"],
     "desc":"Given a GitHub repo URL, pull file tree and code, auto-generate a professional README.md."},
    {"day":9,  "title":"Translation & Localization Tool",       "phase":"beginner",     "tags":["NLP","i18n","Python"],
     "desc":"Translate text across 10 languages while preserving tone and technical terminology."},
    {"day":10, "title":"AI Flashcard Generator",                "phase":"beginner",     "tags":["Education","Anki","JSON"],
     "desc":"Paste any article, generate Anki-compatible Q&A flashcards exported to CSV format."},
    {"day":11, "title":"Natural Language SQL Generator",        "phase":"beginner",     "tags":["SQL","DevTools","NLP"],
     "desc":"Type a plain-English question, receive a valid SQL query for a given schema with explanation."},
    {"day":12, "title":"AI Unit Test Writer",                   "phase":"beginner",     "tags":["Testing","pytest","Python"],
     "desc":"Given a Python function, auto-generate pytest tests for normal, edge, and error cases."},
    {"day":13, "title":"Semantic Search Over Documents",        "phase":"beginner",     "tags":["Embeddings","Search","Python"],
     "desc":"Embed markdown docs, build a local search index, query with natural language using cosine similarity."},
    {"day":14, "title":"AI Meeting Notes Summarizer",           "phase":"beginner",     "tags":["NLP","Productivity","Extraction"],
     "desc":"Feed a meeting transcript, extract action items, decisions, owners, and a 3-line summary."},
    # INTERMEDIATE — Days 15-35
    {"day":15, "title":"RAG Chatbot Over PDF",                  "phase":"intermediate", "tags":["RAG","ChromaDB","LangChain"],
     "desc":"Full RAG pipeline: load PDF, chunk, embed, store in ChromaDB, chat with retrieved context."},
    {"day":16, "title":"LangChain ReAct Agent with Tools",      "phase":"intermediate", "tags":["Agents","LangChain","Tools"],
     "desc":"ReAct agent with web search, Python REPL, and Wikipedia tools. Understand reasoning loops."},
    {"day":17, "title":"Multi-Turn Customer Support Bot",       "phase":"intermediate", "tags":["FastAPI","Memory","KB"],
     "desc":"Support chatbot with conversation memory, knowledge base retrieval, and escalation logic."},
    {"day":18, "title":"AI Code Reviewer GitHub Action",        "phase":"intermediate", "tags":["GitHub Actions","CI","PR"],
     "desc":"GitHub Action on every PR that reviews the diff and posts inline review comments automatically."},
    {"day":19, "title":"Vector Database Comparison",            "phase":"intermediate", "tags":["Pinecone","Qdrant","ChromaDB"],
     "desc":"Same RAG system in three vector DBs. Benchmark query speed, recall@k, and developer experience."},
    {"day":20, "title":"LLM Evaluation Framework",              "phase":"intermediate", "tags":["Evals","RAGAS","Metrics"],
     "desc":"Harness measuring accuracy, hallucination rate, and latency. RAGAS faithfulness and relevance scores."},
    {"day":21, "title":"AI-Powered Data Analyst",               "phase":"intermediate", "tags":["Pandas","Code gen","CSV"],
     "desc":"Upload CSV, ask natural language questions, get auto-generated Pandas code executed in a sandbox."},
    {"day":22, "title":"Embedding-Based Recommender",           "phase":"intermediate", "tags":["Embeddings","UMAP","ML"],
     "desc":"Product embeddings, nearest-neighbour recommendations, UMAP cluster visualisation."},
    {"day":23, "title":"Automated Blog Post Generator",         "phase":"intermediate", "tags":["Content","SEO","LangChain"],
     "desc":"Keyword → research → outline → full SEO post with meta description. Multi-step LangChain chain."},
    {"day":24, "title":"AI Data Cleaning Pipeline",             "phase":"intermediate", "tags":["ETL","Pandas","Validation"],
     "desc":"Feed messy CSV; LLM identifies and fixes format issues, deduplication, and missing values with audit log."},
    {"day":25, "title":"Smart Email Reply Assistant",           "phase":"intermediate", "tags":["Gmail API","NLP","OAuth"],
     "desc":"Read Gmail thread, draft 3 reply options (formal/friendly/concise), one-click draft insertion."},
    {"day":26, "title":"Codebase Q&A Bot",                      "phase":"intermediate", "tags":["RAG","GitHub","tree-sitter"],
     "desc":"Index a GitHub repo with code-aware chunking, chat with it. Understands functions and classes."},
    {"day":27, "title":"LLM Test Data Generator",               "phase":"intermediate", "tags":["Testing","Faker","JSON Schema"],
     "desc":"Describe a schema; generate realistic fake data with edge cases and constraint violations for QA."},
    {"day":28, "title":"Multi-Modal Image Captioner",           "phase":"intermediate", "tags":["Vision","GPT-4o","Batch"],
     "desc":"Upload images, generate captions, extract text, identify objects. Batch-process image folders."},
    {"day":29, "title":"AI API Gateway with Rate Limiting",     "phase":"intermediate", "tags":["FastAPI","Redis","Middleware"],
     "desc":"Proxy for LLM APIs: per-user rate limits, request logging, cost tracking, model fallback, JWT auth."},
    {"day":30, "title":"Automated PR Description Writer",       "phase":"intermediate", "tags":["GitHub Actions","CI","DevTools"],
     "desc":"Git diff → professional PR description with breaking-change detection on PR open."},
    {"day":31, "title":"AI Log Analyser",                       "phase":"intermediate", "tags":["DevOps","NLP","Observability"],
     "desc":"Paste server logs; LLM identifies error patterns, root causes, and remediation steps."},
    {"day":32, "title":"Fine-Tuning with LoRA/PEFT",            "phase":"intermediate", "tags":["Fine-tuning","LoRA","HuggingFace"],
     "desc":"Fine-tune Mistral-7B on custom data with LoRA. Track training loss and evaluate accuracy gain."},
    {"day":33, "title":"AI Interview Question Generator",       "phase":"intermediate", "tags":["HR Tech","Education","JSON"],
     "desc":"Job description → behavioural + technical questions with model answers and scoring rubrics."},
    {"day":34, "title":"Streaming LLM API with FastAPI",        "phase":"intermediate", "tags":["FastAPI","SSE","Streaming"],
     "desc":"Token-by-token streaming via Server-Sent Events. Handle cancellation and backpressure correctly."},
    {"day":35, "title":"Semantic Document Diff Tool",           "phase":"intermediate", "tags":["Embeddings","NLP","Contracts"],
     "desc":"Compare documents by meaning, not just lines. Highlights semantically changed clauses."},
    # ADVANCED — Days 36-50
    {"day":36, "title":"Production RAG with Re-Ranking",        "phase":"advanced",     "tags":["RAG","BM25","Re-ranking"],
     "desc":"Hybrid BM25+vector search, cross-encoder re-ranking, query expansion. Measure NDCG improvement."},
    {"day":37, "title":"LLM Observability Dashboard",           "phase":"advanced",     "tags":["Tracing","MLOps","Metrics"],
     "desc":"Instrument every LLM call. Dashboard: latency percentiles, cost per session, quality scores."},
    {"day":38, "title":"Auto-Healing CI/CD with AI",            "phase":"advanced",     "tags":["DevOps","Agents","GitHub Actions"],
     "desc":"Failed CI → LLM analyses logs → proposes fix → opens PR. Agentic loop with safety guardrails."},
    {"day":39, "title":"Multi-Agent Research System",           "phase":"advanced",     "tags":["Agents","AutoGen","Research"],
     "desc":"Planner + researcher + writer + critic agents collaborate on structured research reports."},
    {"day":40, "title":"Real-Time AI Fraud Detection",          "phase":"advanced",     "tags":["Streaming","MLOps","Rules"],
     "desc":"Stream transactions; LLM+rules engine scores for fraud. Compare with XGBoost model."},
    {"day":41, "title":"AI Infrastructure Provisioner",         "phase":"advanced",     "tags":["Terraform","IaC","Agents"],
     "desc":"Describe infra in English → Terraform plan → review → apply. Blast-radius estimation included."},
    {"day":42, "title":"Guardrails & Safety Layer",             "phase":"advanced",     "tags":["Safety","PII","Injection"],
     "desc":"Input/output filters: PII detection, prompt injection detection, content moderation, fallbacks."},
    {"day":43, "title":"Hybrid Search Engine",                  "phase":"advanced",     "tags":["BM25","Qdrant","RRF"],
     "desc":"BM25 + dense vector search fused with Reciprocal Rank Fusion. Benchmark recall@k."},
    {"day":44, "title":"AI SQL Query Optimiser",                "phase":"advanced",     "tags":["SQL","EXPLAIN","Performance"],
     "desc":"Slow query in → optimised alternatives with index suggestions. Validated with EXPLAIN ANALYSE."},
    {"day":45, "title":"Autonomous Code Refactoring Agent",     "phase":"advanced",     "tags":["Agents","AST","Testing"],
     "desc":"Agent detects code smells via AST, refactors, runs tests to verify no regressions."},
    {"day":46, "title":"AI A/B Test Analyser",                  "phase":"advanced",     "tags":["Stats","Python","Product"],
     "desc":"A/B data → statistical significance, effect size, go/no-go recommendation with confidence intervals."},
    {"day":47, "title":"Multi-Modal Document Intelligence",     "phase":"advanced",     "tags":["Vision","OCR","RAG"],
     "desc":"PDF with charts, tables, images → extract all content → RAG over unified index."},
    {"day":48, "title":"ML Deployment Pipeline with MLflow",    "phase":"advanced",     "tags":["MLflow","MLOps","Canary"],
     "desc":"Train, log, register, stage, deploy, monitor with MLflow. Canary deployment logic included."},
    {"day":49, "title":"Distributed Inference with vLLM",       "phase":"advanced",     "tags":["vLLM","Self-hosting","Perf"],
     "desc":"Self-host Mistral with vLLM continuous batching. Load test and measure tokens/sec."},
    {"day":50, "title":"AI Security Vulnerability Scanner",     "phase":"advanced",     "tags":["Security","OWASP","SAST"],
     "desc":"Scan code for OWASP Top 10 vulnerabilities. Output annotated diffs with remediation code."},
    # EXPERT — Days 51-60
    {"day":51, "title":"Production RAG Evaluation Suite",       "phase":"expert",       "tags":["Evals","RAGAS","Regression"],
     "desc":"End-to-end eval: retrieval P/R, faithfulness, relevance. Automated regression gating on deploy."},
    {"day":52, "title":"LLM Compiler with DSPy",                "phase":"expert",       "tags":["DSPy","Auto-prompt","Optimisation"],
     "desc":"DSPy auto-optimises prompts for a task. Measure accuracy on held-out set vs hand-crafted prompts."},
    {"day":53, "title":"Knowledge Graph + RAG Hybrid",          "phase":"expert",       "tags":["Neo4j","GraphRAG","Multi-hop"],
     "desc":"Knowledge graph from documents + vector RAG for multi-hop reasoning tasks."},
    {"day":54, "title":"On-Device LLM with Ollama",             "phase":"expert",       "tags":["Ollama","Edge AI","Privacy"],
     "desc":"Privacy-first assistant with Mistral running locally. Zero data leaves the device."},
    {"day":55, "title":"AI-Native Feature Flag System",         "phase":"expert",       "tags":["Feature flags","MLOps","Agents"],
     "desc":"LLM decides feature exposure based on user behaviour. Integrates with LaunchDarkly API."},
    {"day":56, "title":"Continuous Pre-Training Pipeline",      "phase":"expert",       "tags":["Training","Tokeniser","W&B"],
     "desc":"Domain-adaptive pre-training on custom corpus. Tokeniser tuning, perplexity tracking with W&B."},
    {"day":57, "title":"LLM-as-Judge Evaluation System",        "phase":"expert",       "tags":["Evals","Alignment","Preference"],
     "desc":"GPT-4 judges outputs of smaller models. Build preference dataset for supervised fine-tuning."},
    {"day":58, "title":"Agentic Software Engineer",             "phase":"expert",       "tags":["Agents","SWE-bench","GitHub"],
     "desc":"Reads GitHub issue, writes code, runs tests, opens PR. SWE-bench inspired autonomous agent."},
    {"day":59, "title":"Multi-Tenant AI Platform API",          "phase":"expert",       "tags":["SaaS","FastAPI","Multi-tenant"],
     "desc":"Per-tenant model config, billing hooks, usage quotas, audit logs. Production SaaS API pattern."},
    {"day":60, "title":"End-to-End AI Production System",       "phase":"expert",       "tags":["Capstone","Full-stack","MLOps"],
     "desc":"Capstone: RAG + agents + evals + observability + CI/CD in one cohesive production system."},
]

def get_project(day: int) -> dict | None:
    return next((p for p in PROJECTS if p["day"] == day), None)
