"""Update README.md and PROGRESS.md after each project deploy."""

import os, sys, json, glob
from datetime import date
sys.path.insert(0, os.path.dirname(__file__))
from projects_registry import PROJECTS

def load_completed():
    done = []
    for f in sorted(glob.glob("day-*/meta.json")):
        with open(f) as fp:
            done.append(json.load(fp))
    return done

def readme(completed):
    pct = int(len(completed) / 60 * 100)
    bar = "█" * int(pct/5) + "░" * (20 - int(pct/5))
    done_days = {c["day"] for c in completed}

    recent = ""
    if completed:
        last = completed[-1]
        recent = f"> **Latest → Day {last['day']}:** [{last['title']}](day-{last['day']:02d}-*/)\n> {last.get('concepts','')}\n"

    phase_counts = {}
    for c in completed:
        phase_counts[c["phase"]] = phase_counts.get(c["phase"], 0) + 1
    stats = " · ".join(f"{v} {k}" for k, v in phase_counts.items()) if phase_counts else "Starting soon..."

    rows = ["| Day | Project | Phase | Status |", "|-----|---------|-------|--------|"]
    for p in PROJECTS:
        status = "✅" if p["day"] in done_days else "⬜"
        rows.append(f"| {p['day']:2d} | {p['title']} | {p['phase'].capitalize()} | {status} |")
    table = "\n".join(rows)

    return f"""# 60 Days of AI in Software Development

> One complete AI project per day — beginner to expert.  
> Auto-generated by **GitHub Models** (free!) via GitHub Actions.  
> [sushantraut007](https://github.com/sushantraut007)

## Progress

```
[{bar}] {pct}% — {len(completed)}/60 complete
```

{stats}

{recent}
## Each project includes

- `README.md` — Problem · Solution · Architecture · Code walkthrough
- `main.py` — Complete working code with inline explanations
- `test_main.py` — pytest unit tests
- `requirements.txt` — All dependencies
- `.env.example` — Required environment variables
- `Dockerfile` — Container setup (where applicable)

## Curriculum

| Phase | Days | Focus |
|-------|------|-------|
| Beginner | 1–14 | Core AI APIs, prompting, basic NLP |
| Intermediate | 15–35 | RAG, agents, LangChain, fine-tuning |
| Advanced | 36–50 | Production MLOps, multi-agent systems |
| Expert | 51–60 | DSPy, GraphRAG, autonomous agents |

## How it works

1. GitHub Actions runs at **9 AM UTC** every day (free)
2. `calculate_day.py` determines today's project number
3. `generate_project.py` calls **GitHub Models** (gpt-4o, free) to generate everything
4. Project folder committed + pushed automatically
5. This README updated with live progress

**Zero cost** — uses only `GITHUB_TOKEN` (built into every repo).

## Setup — fork & go

```bash
# 1. Fork this repo
# 2. Settings → Variables → Actions → New variable:
#    PROJECT_START_DATE = 2025-06-01
# 3. Settings → Actions → Workflow permissions → Read and write
# 4. Actions tab → Daily AI Project Deploy → Run workflow
```
No API keys. No credit card. Fully free.

## Project index

{table}

---
*Last updated: {date.today().isoformat()} · Powered by GitHub Models*
"""

def progress_md(completed):
    lines = [f"# Progress Log\n\nUpdated: {date.today().isoformat()}\n"]
    for c in completed:
        lines.append(f"## Day {c['day']}: {c['title']}")
        lines.append(f"**Phase:** {c['phase'].capitalize()}  ")
        lines.append(f"**Concepts:** {c.get('concepts', 'N/A')}  ")
        lines.append(f"**Folder:** `day-{c['day']:02d}-*/`\n")
    return "\n".join(lines)

def main():
    completed = load_completed()
    print(f"Completed: {len(completed)} projects")
    with open("README.md",   "w") as f: f.write(readme(completed))
    with open("PROGRESS.md", "w") as f: f.write(progress_md(completed))
    print("Updated README.md and PROGRESS.md")

if __name__ == "__main__":
    main()
